### ISSUE TITLE
Property 'send' does not exist on type 'typeof Pushover'

### ISSUE THREAD

**Issue by cjazinski** [danitetus/pushover-js#19]
I'm using 1.3.1 and following the TS example (promises) found in the docs

**Comment by cjazinski** [comment]
I was able to resolve this. I changed line

`const response = await Pushover.send('Submit an issue', 'Click on the link to submit an issue')`

to

`const response = await pushover.send('Submit an issue', 'Click on the link to submit an issue')`

**Comment by d4nicoder** [comment]
You are right, there is a typo in the examples. I'll fix it soon.

Thank you for the report @cjazinski
