### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by lacabra** [danitetus/pushover-js#2]
Hola @danitetus 👋

I used this library in April, May and June of this year without a problem. Everything worked great! 🙏

Today, I've run the same code, and I'm getting this error out of the blue, throwing an exception:
```
undefined:1
{"status":1,"request":"43e6b20f-
                                

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (node_modules/pushover-js/lib/pushover.js:157:21)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.Readable.read (_stream_readable.js:503:10)
    at flow (_stream_readable.js:972:34)
    at resume_ (_stream_readable.js:953:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

It really looks like that something has changed in the API endpoint. It's also worth noting that the first two lines above `undefined:1     {"status":1,"request":"43e6b20f-` are not from my code, they are output by `pushover-js`.

Also, it is strange because I cannot catch this exception: even when I wrap the `notifications.send()` call around a `try{...} catch` clause, the exception throws and program aborts.

Have you seen this before? or do you have any idea why this may be happening?

Gracias!

**Comment by d4nicoder** [comment]
Hi @lacabra 
Thanks for the report. The problem was that not all the chunks of the response were stored. Check the solution please.
The new version on NPM is 0.0.3.

PS: I want to rewrite this library to implement async / await in calls. Let's see if I have a little time this week and I will.

**Comment by lacabra** [comment]
Wow! you are fast 🚀   Yes, your latest commit fixes this issue. Thank you very much, Daniel.
